### ISSUE TITLE
Rate xsd definition should use decimal instead of float

### ISSUE THREAD

**Issue by AlexanderYastrebov** [iggyzap/exchange-rates#1]
Rate xsd definition should use decimal instead of float as float could not represent some numbers precisely (e.g. 1.0748)

https://github.com/iggyzap/exchange-rates/blob/master/play-module/app/models/iggy/zap/schema/ecb-cube.xsd#L25

Generated JAXB binding will use BigDecimal instead of Float.

See also http://docs.oracle.com/cd/E19957-01/806-3568/ncg_goldberg.html

**Comment by iggyzap** [comment]
If you submit a pull request I'll happily merge it in. Quite unexpected that someone is using this module :)

**Comment by AlexanderYastrebov** [comment]
Hi.
I fixed that in our project where we use the same xsd files.
I tried to find origins of this xsd's and was only able to find this repo.

Did you wrote them or borrowed from somewhere else? 
I latter case, please, could you try to figure out where do they come from?

**Comment by AlexanderYastrebov** [comment]
Making PR will require changes beside schema update.

**Comment by iggyzap** [comment]
Well, most probably I've derived simple schema file from ECB xml file. 

Since I've no interest in working with any play framework stuff, and I no longer have machine that used to have project with all dependencies and there is no will to provide PR, I will not do anything to address the issue.

PS. This project is a 2-day demo, and is not meant to be used in production.

**Comment by AlexanderYastrebov** [comment]
I would personally leave it open so others can stumble upon it before copying blindly as it happened in our case :)

Anyhow thanks for quick feedback!

**Comment by iggyzap** [comment]
I think what I can do with xsd - if I'll have some spare time I might pull it out as separate maven-build project for further reference, since it's really backward to define money as float.

**Comment by AlexanderYastrebov** [comment]
For example here classes are written manually https://github.com/oliverdm/eurofxref-jaxb and rate is used as a string. In our case I just changes from `xs:float` to `xs:decimal` and this resulted in rate of type `BigDecimal` after class generation.

**Comment by AlexanderYastrebov** [comment]
> I think what I can do with xsd - if I'll have some spare time I might pull it out as separate maven-build project for further reference, since it's really backward to define money as float.

I am not sure whether play module without support has value, but pure schemas have for sure :)
